app_site_index:
    path: /
    controller: App\Controller\Site\IndexController::index
    methods: [GET]

app_site_security:
    resource: site/security.yaml
    prefix: /

app_site_ticket:
    resource: site/ticket.yaml
    prefix: /ticket
